
# #
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: install_ubuntu
  pool: 5
  username: postgres
  password: admin

  development:
  adapter: postgresql
  encoding: unicode
  database: install_ubuntu_pro
  pool: 5
  username: postgres
  password: admin